- name: Pull and Run docker image
  hosts: macos
  tasks:
    - name: Start docker service
      service:
        name: docker
        state: started

    - name: Pull pratyush02/devops_calculator
      docker_image:
        name: pratyush02/devops_calculator
        source: pull